# require: rubocop-privacy

AllCops:
  Exclude:
    - vendor/**/*

Metrics/AbcSize:
  Exclude:
    - spec/**/*

Style/Documentation:
  Exclude:
    - spec/**/*

Style/FileName:
  Exclude:
    - lib/rubocop-privacy.rb

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys