language: ruby

sudo: false

cache: bundler

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

before_install:
  - gem update --system --no-ri --no-rdoc
  - gem update --remote --bundler